#!./.venv/bin/python

"""
Author            : Nohavye
Author's Email    : noha.poncelet@gmail.com
Repository        : https://github.com/vixen-shell/vixen-client.git
Description       : vixen display client executable.
License           : GPL3
"""

import argparse
from vixen_client_lib import ClientStarter

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = f"""
        Client to launch Vixen Shell layers and windows.
    """)

    parser.add_argument('--feature', '-f', type = str, help = 'Feature Name.')
    parser.add_argument('--id', '-i', type = str, help = 'Feature Id.')

    args = parser.parse_args()

    ClientStarter().start(args.feature, args.id)