#!./.venv/bin/python

"""
Author            : Nohavye
Author's Email    : noha.poncelet@gmail.com
Repository        : https://github.com/vixen-shell/vixen-client.git
Description       : vixen display client executable.
License           : GPL3
"""

import argparse
from vixen_client_lib import ClientStarter

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = f"""
        Client to launch Vixen Shell layers and windows.
    """)

    parser.add_argument('--feature', '-f', type = str, help = 'Feature Name.')
    parser.add_argument('--id', '-i', type = str, help = 'Feature Id.')
    parser.add_argument('--dev', '-d', default = False, type = bool, help = "Development mode. (Use 'devUrl' parameters in the configuration file.)")

    args = parser.parse_args()

    client_starter = ClientStarter(args.id)
    client_starter.start(args.feature, args.dev)